#define LEER_MODO 10
#define CAMBIAR_MODO 11
#define MODO_EMERGENCIA 0
#define MODO_INACTIVO 1
#define MODO_NAVEGACION 2
#define MODO_SONDEO 3
#define CONFIRMAR_LLEGADA 20
#define RECIBIR_DIRECCION_DISTANCIA_OBJ 30
